server.port: ${APP_PORT:8080}
spring:
  threads.virtual.enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}/${POSTGRES_DB:rinha}
    username: ${POSTGRES_USER:rinha}
    password: ${POSTGRES_PASSWORD:rinha}
    hikari:
      maximum-pool-size: ${APP_DB_MAX_POOL_SIZE:15}
  jackson:
    deserialization:
      accept-float-as-int: false
